version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.1.0
    environment:
      - APP_ID: pekgbpmeppfghkiaaolmjhiooapokgbk
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update
            sudo apt-get -y install curl jq
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build package
          command: |
            npm run build:prod
      - store_artifacts:
          path: out/out.zip
          destination: ./package.zip
      - run:
          name: Build canary package
          command: |
            npm run build:canary
      - store_artifacts:
          path: out/out.zip
          destination: ./canary.zip
      - run:
          name: "Upload & Publish Extension to the Google Chrome Store"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T out/out.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
            fi


