version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2.1
    environment:
      - APP_ID: pekgbpmeppfghkiaaolmjhiooapokgbk
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update
            sudo apt-get -y install curl jq
      # - restore_cache:
      #     keys:
      #     - npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - store_artifacts:
          path: /home/circleci/.npm/_logs
          destination: ./npm-logs/
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build package
          command: |
            npm run build:prod
      - store_artifacts:
          path: out/out.zip
          destination: ./package.zip
      - run:
          name: Build canary package
          command: |
            npm run build:canary
      - store_artifacts:
          path: out/out.zip
          destination: ./canary.zip
      - run:
          name: "Upload Extension to the Google Chrome Store"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
              UPLOAD_RESULT=(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T out/out.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}")
              echo Package uploaded
              echo $UPLOAD_RESULT
              if [ "$(echo $UPLOAD_RESULT | jq -r .uploadState)" == "FAILURE" ]; then
                echo *********************************************************************
                echo Package validation failed
                echo Error: $(echo $result | jq .itemError | jq -r first.error_code)
                echo Detail: $(echo $result | jq .itemError | jq -r first.error_detail)
                echo *********************************************************************
                exit 1
              fi
            fi
      - run:
          name: "Publish Extension to the Google Chrome Store"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              PUBLISH_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish" | jq .uploadState)
              echo Package published
              echo $PUBLISH_RESULT
              if [ "$(echo $PUBLISH_RESULT | jq -r .status)" != "["OK"]" ]; then
                echo *********************************************************************
                echo Status: $(echo $PUBLISH_RESULT | jq -r .status)
                echo Detail: $(echo $PUBLISH_RESULT | jq -r .statusDetail)
                echo *********************************************************************
                exit 1
              fi
            fi


